CREATE TABLE IF NOT EXISTS `artist` (
	`artist_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`artist_name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`artist_id`)
);


CREATE TABLE IF NOT EXISTS `country` (
	`country_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`country_code` CHAR(2) NOT NULL UNIQUE,
	`country_name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`country_id`)
);


CREATE TABLE IF NOT EXISTS `genre` (
	`genre_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`genre_name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`genre_id`)
);


CREATE TABLE IF NOT EXISTS `track` (
	`trackID` VARCHAR(255) NOT NULL,
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`title` VARCHAR(255) NOT NULL,
	`explicit` BOOLEAN NOT NULL,
	`duration` FLOAT NOT NULL,
	PRIMARY KEY(`trackID`)
);


CREATE TABLE IF NOT EXISTS `charts` (
	`chart_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`country` VARCHAR(2) NOT NULL,
	`trackID` VARCHAR(255) NOT NULL,
	`date` YEAR NOT NULL,
	`streams` INTEGER NOT NULL,
	`position` INTEGER NOT NULL,
	PRIMARY KEY(`chart_id`)
);


CREATE TABLE IF NOT EXISTS `track_genre` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`trackID` VARCHAR(255) NOT NULL,
	`genre_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `track_artist` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`trackID` VARCHAR(255) NOT NULL,
	`artist_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `charts_countries` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`chart_id` INTEGER NOT NULL,
	`country_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `charts`
ADD FOREIGN KEY(`trackID`) REFERENCES `track`(`trackID`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `track_artist`
ADD FOREIGN KEY(`trackID`) REFERENCES `track`(`trackID`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `track_genre`
ADD FOREIGN KEY(`trackID`) REFERENCES `track`(`trackID`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `track_artist`
ADD FOREIGN KEY(`artist_id`) REFERENCES `artist`(`artist_id`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `charts_countries`
ADD FOREIGN KEY(`chart_id`) REFERENCES `charts`(`chart_id`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `charts_countries`
ADD FOREIGN KEY(`country_id`) REFERENCES `country`(`country_id`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `track_genre`
ADD FOREIGN KEY(`genre_id`) REFERENCES `genre`(`genre_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;